/**
 * What every table header means, in plain words — one registry for the whole dashboard.
 *
 * Every <th> renders an (i) from here (see components/header-info.tsx and FilterTable).
 * Look-up is by the header's text, case-insensitive; a page can override a label whose
 * meaning differs there (PAGE_HEADER_HELP, keyed by route prefix). Column definitions that
 * carry their own `info:` keep it — this is the fallback that guarantees no header is mute.
 *
 * Write for the person who has never seen the page: what the column holds, where it comes
 * from, and how to read it. Trade terms (DOQ, EE, TNA, FOB, GRN, SKU, EDD) are the team's
 * daily vocabulary and are used as-is.
 */

const norm = (label: string) =>
  label
    .replace(/\s+/g, ' ')
    .replace(/[:*]+$/g, '')
    .trim()
    .toLowerCase()
    // the LIVE / FIXED tags rendered inside a header are not part of its name
    .replace(/\s+(live|fixed)$/, '');

/** Labels whose meaning is the same wherever they appear. */
const GLOBAL: Record<string, string> = {
  // ---- identity
  'sku': 'The stock-keeping unit: one product in one colour and one size — the finest thing that can be in or out of stock. Product code + colour + size.',
  'variant': 'The product in one colour (product code + colour), all sizes together. Called the colour elsewhere.',
  'product variant': 'The product in one colour (product code + colour), all sizes together.',
  'product': 'The product code — one style across all its colours and sizes, e.g. SDFLK. The product master calls this the category.',
  'product code': 'One style across all its colours and sizes, e.g. SDFLK. The product master calls this the category.',
  'product name': "The product's name as the product master holds it.",
  'product / colour': 'The product code, or the product code with its colour when the view is by colour.',
  'colour': 'The colour of the product on this row, from the product master.',
  'colour / variant': 'The colour of the product on this row (the variant), from the product master.',
  'colour / size': 'The colour and size on this row — together they make the SKU.',
  'size': 'The garment size (XS … 5XL, or free size).',
  'vendor': 'The vendor (manufacturer) on this row, with its code — the code is what every other page uses to identify the vendor.',
  'vendor code': "The vendor's short code (e.g. KVN). Every page identifies a vendor by this.",
  'merchant': 'The merchandiser at SAADAA who manages this vendor, from the vendor master.',
  'merchandiser': 'The merchandiser at SAADAA who manages this vendor, from the vendor master.',
  'po': 'The purchase order reference. One PO can carry several products and colours.',
  'request id': 'The unique id of this PO request (PR-YYMM-0001), assigned when the draft is saved. The EasyCom PO number is linked to it at issuance — no PO number is generated on the dashboard.',
  'po ref': 'The purchase order reference (e.g. FY26-27/FOB/SDFLK/KVN-03). One PO can carry several products and colours.',
  'po ref num': 'The purchase order reference (e.g. FY26-27/FOB/SDFLK/KVN-03).',
  'po no': 'The PO number as EasyEcom holds it.',
  'po no.': 'The PO number as EasyEcom holds it.',
  'po number': 'The PO number as EasyEcom holds it.',
  'po references': 'The purchase orders behind this row, by reference.',
  'po type': 'How the PO is contracted: Job Work (SAADAA supplies fabric, vendor stitches), E-FOB or FOB (vendor supplies fabric too). Sets the lead time and how the value is priced.',
  'type': 'The PO type: Job Work (SAADAA supplies fabric, vendor stitches), E-FOB or FOB (vendor supplies fabric too). Sets lead time and pricing.',
  'category': 'The product category from the product master.',
  'sub-category': 'The finer product category from the product master (Shirt, Casual Pant, Long Kurta…).',
  'weave': 'Woven or Knitted, from the product master. The two fabric pools are planned and sourced separately.',
  'weave type': 'Woven or Knitted, from the product master.',
  'woven / knitted': 'Whether the product is a woven or a knitted garment, from the product master.',
  'gender': 'Who the product is for — Men, Women, Unisex — from the product master.',
  'warehouse': 'The warehouse this stock row belongs to. Main Warehouse serves online orders and is the one demand is measured at.',
  'product state': 'Where the product is in its life: Ongoing (selling), NPD (new, launched), NPD Not Launched Yet, SKU-Create, To Be Discontinued, Discontinued. This is separate from the sales class (A/B/C/D).',
  'status': 'Where this row stands right now. Hover the value for the rule behind it.',
  'state': 'Where this row stands in its workflow — Draft, Approval Pending, Rework, Approved or Rejected.',
  'class': 'The sales class from how fast the product sells: A above 10 a day, B 7 or more, C 3 or more, else D (thresholds in Rules Master). Speed only — D does not mean discontinued.',
  // ---- quantities and money
  'qty': 'Pieces on this row.',
  'quantity': 'Pieces on this row.',
  'total qty': 'Pieces ordered on the PO, summed over every line.',
  'total quantity': 'Pieces on this row, summed over every PO type or line.',
  'ordered': 'Pieces ordered on the PO.',
  'pending': 'Pieces ordered but not yet received — ordered minus received.',
  'pending qty': 'Pieces ordered but not yet received — ordered minus received.',
  'pending actual': 'Pieces still to arrive after manual adjustments are applied — the figure every open-PO number on the dashboard uses.',
  'original': 'Pieces originally ordered on the line, before any receipt or adjustment.',
  'received': 'Pieces that have physically arrived (goods receipt).',
  'price': 'The per-piece price on the PO line. Job Work lines carry the stitching rate only, not a garment price.',
  'value': 'Pieces × the rate on this row, in rupees.',
  'total': 'The sum of the row (or of the column, on a total row).',
  'total value': 'Pieces × rate, summed over the row.',
  'open value': 'Money still committed on open POs: pending pieces × item price. Job Work lines are priced at the stitching rate.',
  'open qty': 'Pieces still to arrive on open POs.',
  'open pos': 'How many purchase orders are open — counted as PO numbers, not lines.',
  'share': 'This row as a share of the column total.',
  'cost': 'The cost price per piece as the product master holds it.',
  'mrp': 'The maximum retail price per piece, from the product master.',
  // ---- dates and time
  'edd': 'Expected delivery date — when the goods are due to arrive, from the PO. Past this date with pieces pending = overdue.',
  'delay': 'Days past the expected delivery date with pieces still pending. 0 = not late.',
  'delay %': 'Late POs ÷ open POs for this row, as a percentage.',
  'delayed': 'How many of the open POs are past their expected delivery date.',
  'days': 'Whole days, counted as the header says.',
  'days open': 'Whole days since the row was raised or opened.',
  'last updated': 'When this row was last saved, and by whom where shown.',
  'last set': 'When this value was last entered.',
  'created': 'When the record was created.',
  'created by': 'Who created the record.',
  'by': 'Who did it — the signed-in user at the time.',
  'when': 'When it happened.',
  'on': 'The date it happened.',
  'synced': 'When this row was last copied from its source (BigQuery, EasyEcom or the sheet). If it is old, check Sync Health.',
  'snapshot': 'The date of the nightly stock snapshot this row is from.',
  'month': 'The calendar month this row belongs to.',
  'ingested': 'When this row reached the dashboard from its source feed.',
  // ---- people and workflow
  'requested by': 'Who raised the request — the signed-in user at the time.',
  'raised by': 'Who raised it. "Dashboard check" means the dashboard raised it from one of its own data checks.',
  'assigned to': 'Who is responsible for resolving it now. Unassigned means nobody has picked it up and no route was set.',
  'decision': 'Approve, reject or send back — shown only to someone allowed to decide. The first decision wins.',
  'approval': 'Where the row stands in the approval flow: Draft, Approval Pending, Rework, Approved or Rejected.',
  'actor': 'Who made the change.',
  'notes': 'The note left with the change — required for a reject or rework.',
  'remark': 'A free note on the row.',
  'remarks': 'Free notes on the row.',
  'reason': 'The reason given, in the words of whoever gave it.',
  'note': 'A free note on the row.',
  'action': 'What you can do with this row from here.',
  'actions': 'What you can do with this row from here.',
  'via': 'How the entry arrived — typed on the dashboard, or through a data-capture link.',
  'active': 'Whether the record is in use. Inactive rows are kept for history but not offered in pickers.',
  'enabled': 'Whether this is switched on.',
  // ---- stock and demand
  'current stock': 'Sellable pieces in stock as of the nightly snapshot.',
  'stock': 'Sellable pieces in stock as of the nightly snapshot.',
  'in process': 'Pieces on approved POs that have not yet been received — on order.',
  'on order (in process)': 'Pieces on approved POs that have not yet been received.',
  'doq': 'Daily Order Quantity — pieces a day this sells, from sales ÷ days in stock.',
  'doq (45d)': 'Daily Order Quantity over the last 45 days — pieces sold ÷ days in stock in the window. Empty days do not drag it down.',
  'doq 15': 'Pieces a day sold over the last 15 days (sales ÷ days in stock).',
  'doq 30': 'Pieces a day sold over the last 30 days (sales ÷ days in stock).',
  'doq 45': 'Pieces a day sold over the last 45 days (sales ÷ days in stock). The figure ordering is built on.',
  'doq 90': 'Pieces a day sold over the last 90 days (sales ÷ days in stock).',
  'doq 365': 'Pieces a day sold over the last year — the steady, long-window rate.',
  'doq 7-30': 'Pieces a day sold between 7 and 30 days ago.',
  'doq 30-45': 'Pieces a day sold between 30 and 45 days ago.',
  'monthly doq': "The feed's monthly demand rate for the SKU.",
  'yearly doq': "The feed's yearly demand rate for the SKU.",
  'weightage doq': 'The 45-day DOQ with recent days counting for more, from the feed.',
  'oos days 15': 'Days with no stock in this warehouse over the last 15 days.',
  'oos days 30': 'Days with no stock in this warehouse over the last 30 days.',
  'oos days 45': 'Days with no stock in this warehouse over the last 45 days. Per warehouse — the Main Warehouse row is the one that matters.',
  'oos days 90': 'Days with no stock in this warehouse over the last 90 days.',
  'oos days 365': 'Days with no stock in this warehouse over the last 365 days.',
  't7 qty': 'Pieces sold in the last 7 days.',
  't45 qty': 'Pieces sold in the last 45 days.',
  't730 qty': 'Pieces sold in the last 730 days (two years).',
  't730-15 qty': 'Pieces sold in the last 730 days excluding the most recent 15.',
  'sales (45 inv-days)': 'Pieces sold across the days the SKU was in stock in the last 45 — the numerator of DOQ 45.',
  'total qty sold': 'Pieces sold in the 45-day window, counting only days the SKU was in stock.',
  'shopify sp': 'The live selling price on Shopify.',
  'oos lines': 'PO lines whose product is currently out of stock.',
  // ---- capacity
  'machines allocated': 'Machines the vendor has allocated to SAADAA right now — one of the two figures typed each week.',
  'karigar allocated': 'Karigars (tailors) the vendor has allocated to SAADAA right now — one of the two figures typed each week. Capacity is built on this.',
  'code': 'The code that identifies this row.',
  'machines': 'Machines the vendor has allocated to SAADAA, as entered on Vendor Capacity.',
  'active karigar': 'Karigars (tailors) allocated to SAADAA, from the vendor master at onboarding.',
  'latest karigar': 'The most recently entered karigar count from the Vendor Capacity sheet.',
  'capacity / month': 'Pieces the vendor can make in a month: workers × pieces per worker per day × working days a month (all Rules Master values). "Not entered" = nothing on the sheet yet.',
  'capacity/mo': 'Pieces the vendor can make in a month: workers × pieces per worker per day × working days (Rules Master).',
  'po capacity': "Pieces the vendor can make inside its PO type's lead time: capacity/month × lead days ÷ 30. An E-FOB vendor is judged on 45 days of output, a FOB vendor on 75 — this, not the month, is what on-order quantity is compared against.",
  'first machines': 'Machines committed to SAADAA at onboarding — the locked baseline from the vendor master.',
  'available': 'PO capacity minus pieces on order — room for new POs. "Over Utilised" = more on order than the vendor can make in its lead time.',
  'machine util': 'Karigars ÷ machines allocated × 100 — how densely the machines are staffed.',
  'capacity util': 'Pieces on order ÷ PO capacity × 100. Past 100% the cell reads "100% Over Utilised" — beyond capacity the exact figure stops mattering.',
  'utilization': 'Pieces on order ÷ PO capacity × 100. Past 100% it reads "100% Over Utilised" rather than a figure.',
  'utilisation': 'Pieces on order ÷ PO capacity × 100. Past 100% it reads "100% Over Utilised" rather than a figure.',
  'allocated (pcs/month)': 'Pieces a month of this product the vendor is committed to make, as entered on the Product Allocation tab.',
  'job work lead-time': 'Days a Job Work PO takes from issue to delivery (Rules Master).',
  'e-fob lead-time': 'Days an E-FOB PO takes from issue to delivery (Rules Master).',
  'fob lead-time': 'Days a FOB PO takes from issue to delivery (Rules Master).',
  // ---- costing
  'standard': 'The approved Standard Cost per piece for this PO type.',
  'expected': 'The cost the team expected before negotiation.',
  'actual': 'The rate actually written on the PO.',
  'proposed': 'The cost the team proposed at the start of the negotiation.',
  'target': 'The cost the admin set to negotiate toward.',
  'rate': 'The per-piece rate on this row.',
  'stage': 'Where the row is in its process. Hover the value for the rule behind it.',
  'cmtp': 'Cut, Make, Trim and Pack — the stitching-side cost per piece, before fabric.',
  'garment': 'Fabric cost + CMTP — the full cost of one garment before margin.',
  'margin': 'The margin added to the garment cost (Rules Master margin_pct).',
  'final price': 'Garment cost + margin — the approved Standard Cost per piece.',
  'fabric': 'The fabric this row is about, by its fabric code.',
  'fabric code': 'The unique code of the greige (undyed) fabric.',
  'fabric sku': 'The fabric SKU cut for this PO line.',
  'yarn cost': 'The yarn cost per metre that goes into the fabric.',
  'conversion': 'The cost of converting yarn to grey fabric, per metre.',
  'grey rate': 'Yarn + conversion — the grey (undyed) fabric cost per metre.',
  'processing': 'Dyeing and finishing cost per metre.',
  'finished cost': 'Grey rate + processing — the finished fabric cost per metre.',
  'grey (live)': 'The current grey fabric rate on the Fabric Cost master.',
  'finished (live)': 'The current finished fabric rate on the Fabric Cost master.',
  'this month': 'The rate submitted for the current month.',
  'accepted on': 'When this rate was accepted.',
  'revised on': 'When this line was revised.',
  'set by': 'Who set this value.',
  'old': 'The value before the change.',
  'new': 'The value after the change.',
  'line': 'The cost line that changed.',
  // ---- TNA
  'planned (tna)': 'The date this stage was planned for on the TNA (time-and-action) timeline.',
  'actual (pass)': 'The date the stage was actually completed (passed).',
  'on-time / delay': 'Whether the stage was completed by its planned date, and by how many days it was late if not.',
  'inspections': 'Inspection records logged for this stage.',
  'report': 'The inspection report, where one was attached.',
  'pp / gpt / cut / inline': 'The four critical-path TNA stages — PP sample, GPT, cutting, inline QC — with their planned and actual dates.',
  'status · blocking stage': 'The PO status and, when it is High Risk, the TNA stage that is past its planned date with nothing recorded.',
  // ---- misc
  'source': 'Where the feed comes from — BigQuery, a Google Sheet, or EasyEcom.',
  'pipeline': 'The named sync job that copies this feed.',
  'rows': 'How many rows the last refresh landed.',
  'last refreshed': 'When the feed last refreshed. Older than the Rules Master stale threshold = flagged stale.',
  'path': 'The route in the sidebar this row controls.',
  'tab': 'The sidebar tab this row controls.',
  'feature': 'The dashboard feature this row describes.',
  'preview': 'A preview of what the note looks like on the page.',
  'note (optional)': 'A short note shown on the feature; leave blank for none.',
  'person': 'The user, by name.',
  'role': "The user's base role — viewer, team or admin — which sets what they can approve.",
  'access level': "The user's base role — viewer (read), team (raise and submit), admin (approve everything).",
  'roles (views)': 'The custom roles held, which decide which pages the user can see.',
  'name': 'The name.',
  'last login': 'When the user last signed in.',
  'last active': 'When the user last used the dashboard.',
  'last action': "The user's most recent recorded action.",
  'actions 7d': 'Recorded actions by this user in the last 7 days.',
  'actions 30d': 'Recorded actions by this user in the last 30 days.',
  'entries 7d': 'Entries made in this module in the last 7 days.',
  'entries 30d': 'Entries made in this module in the last 30 days.',
  'module': 'The dashboard module the entries belong to.',
  'record': 'The item awaiting a decision — a buying plan, PO, discontinue request or vendor de-boarding.',
  'change': 'The status change that was made.',
  'buying plans': 'Buying plans in the approval queue.',
  'po approvals': 'Purchase orders in the approval queue.',
  'standard cost': 'Standard Cost proposals awaiting sign-off.',
  'discontinue': 'Discontinue requests in the approval queue.',
  'vendor de-boarding': 'Vendor de-boarding requests in the approval queue.',
  'inward plan': 'Inward Plan submissions in the approval queue.',
  'approved': 'Approved.',
  'issued': 'Issued to the vendor.',
  'issue': 'What is wrong, in one line, with the urgency tag when high or blocker. The robot icon means the dashboard raised it from a data check.',
  'about': 'The category of the issue, and the PO, product or vendor code it refers to.',
  'routes to': 'The person issues in this category go to automatically when raised without a name.',
  'save': 'Save the row.',
  'submit': 'Submit the row.',
  'image': 'The product image from the master.',
  'description': 'The description from the master.',
  'hsn': 'The HSN tax classification code.',
  'gst': 'The GST rate applied.',
  'tax rate': 'The tax rate applied.',
  'tax rule': 'The tax rule applied.',
  'model no': 'The model number from the master.',
  'width': 'Width, as held in the master or entered.',
  'height': 'Height, as held in the master.',
  'length': 'Length, as held in the master.',
  'weight': 'Weight, as held in the master.',
  'fit': 'The fit type (regular, slim…), from the product master.',
  'sleeve': 'Sleeve type, from the product master.',
  'neck/collar': 'Neck or collar type, from the product master.',
  'season': 'The season the product belongs to, from the product master.',
  'product type': 'The product type from the product master.',
  'launch date': 'When the product was launched.',
  'category type': 'Top wear, bottom wear or dress, from the product master.',
  'item category': 'Casual, smart casual, ethnic or western, from the product master.',
  'colour family': 'The broader colour family the colour belongs to.',
  'garment length': 'Garment length type, from the product master.',
  'price range': 'The price band the product sells in.',
  'washcare sku': 'The wash-care label SKU attached to the product.',
  'age group': 'The age group the product is for.',
  'composition': 'The fibre composition of the fabric.',
  'gsm': 'Fabric weight in grams per square metre.',
  'fabric cons. avg': 'Metres of fabric one piece takes, on average — the benchmark cutting is checked against.',
  'replen. type': 'Whether the product is meant to be reordered: continuous vs one-time or seasonal.',
  'related ongoing': 'The existing product this new one replaces or extends.',
  'rm code': 'The raw (greige) fabric code the product is cut from.',
  'dyed fabric sku': 'The dyed or finished fabric code the product uses.',
  'qty in metres': 'Despite its name, this EasyEcom field holds gender + wear type (e.g. F TOP WEAR), not a metre quantity.',
  'warp count': 'Yarn count in the warp direction.',
  'weft count': 'Yarn count in the weft direction.',
  'third thread / blend': 'A third yarn or blend in the construction, where present.',
  'raw material / colour': 'The raw material, and the colour for dyed fabric.',
  'raw material': 'Greige (undyed) fabric.',
  'dyed / finished': 'Dyed or finished fabric — a greige fabric in a colour.',
  'trims': 'Trims — buttons, labels, threads and the like.',
  'material code': 'The unique code of the material.',
  'base fabric': 'The greige fabric this dyed fabric is made from.',
  'uom': 'Unit of measure — metres, pieces, kilograms.',
  'job rate': 'The approved Job Work rate per unit for this material.',
  'purchase rate': 'The approved purchase rate per unit for this material.',
  'job work qty': 'Quantity planned through Job Work.',
  'job qty': 'Quantity planned through Job Work.',
  'purchase qty': 'Quantity planned as a straight purchase.',
  'contact no.': 'Phone number of the vendor contact.',
  'email': 'Email address of the vendor contact.',
  'pan': "The vendor's PAN.",
  'msme / udyam': "The vendor's MSME / Udyam registration number.",
  'payment term': 'The agreed payment terms with the vendor.',
  'payment terms (days)': 'Days after invoice the vendor is paid.',
  'delivery term': 'The agreed delivery terms with the vendor.',
  'currency': 'The currency the vendor is paid in.',
  'unregistered': 'Whether the vendor is unregistered for GST.',
  'address': "The vendor's address as held in EasyEcom.",
  'dl expiry': 'Drug licence expiry — an EasyEcom field that does not apply to garment vendors.',
  'fssai no.': 'FSSAI number — an EasyEcom field that does not apply to garment vendors.',
  'fssai expiry': 'FSSAI expiry — an EasyEcom field that does not apply to garment vendors.',
  'freight fwd days': 'Freight-forwarding days EasyEcom holds for the vendor.',
  'prep days': 'Preparation days EasyEcom holds for the vendor.',
  'in-transit days': 'Shipment in-transit days EasyEcom holds for the vendor.',
  'wh check-in': 'Warehouse check-in time EasyEcom holds for the vendor.',
  'vendor token': "The vendor's EasyEcom token.",
  'api token': "The vendor's EasyEcom API token.",
  'grn line id': "EasyEcom's id for this goods-receipt line.",
  'grn id': "EasyEcom's id for the goods receipt.",
  'grn date': 'When the goods were received.',
  'invoice date': "The date on the vendor's invoice.",
  'po id': "EasyEcom's internal id for the PO.",
  'po line id': "EasyEcom's internal id for the PO line.",
  'product id': "EasyEcom's internal id for the product.",
  'vendor c-id': "EasyEcom's internal id for the vendor.",
  'easyecom': 'The PO as it exists in EasyEcom, by number.',
  'colours': 'How many colours the PO carries.',
  'products': 'How many products the PO carries.',
  'signed': 'Whether the signed PO document has been uploaded.',
  'signed docs': 'The signed PO documents uploaded for this PO.',
  'closing': 'The PO closing date from the TNA.',
  'buying plan': 'Whether this PO is in the approved buying plan for its month, or an ad-hoc purchase outside it.',
  'cycle (days)': 'Days from the PO being raised to being issued.',
  'line status': 'The approval state of this colour line, when lines are decided one by one.',
  'vendor (live load)': 'The vendor, with the pieces currently in process with them.',
  'closure': 'Where the PO stands in closure once delivery is complete.',
  'completed': 'When the PO was completed on EasyEcom.',
  'surplus': 'Pieces received above the ordered quantity.',
  'cut date': 'The date the vendor cut this PO line.',
  'item': 'The product on this line.',
  'cut qty': 'Pieces the vendor cut for this line.',
  'avg cons.': 'Metres of fabric one piece is supposed to take — the approved average.',
  'consumed': 'Metres of fabric actually used in cutting.',
  'expires': 'When the data-capture link stops working.',
  'adjust qty': 'The hand correction to the quantity, positive or negative.',
  'adjust qty (±)': 'The hand correction to the quantity — positive adds, negative removes.',
  'bigquery': 'Whether the adjustment has been pushed back to BigQuery.',
  'entered': 'When the adjustment was entered on the dashboard.',
  'why (current stage)': 'Which TNA stage the PO is waiting on, and why it is flagged.',
  'scope': 'What is being discontinued: a size, a colour or the whole product.',
  'oldest (days)': "The age of the oldest still-available unit in the SKU — what drives the ageing bucket.",
  'ageing': 'How old the stock is: New <90 days · Aging 90–180 · Old 180–365 · Dead Stock >365, judged by the oldest unit.',
  'recommended discount': 'A suggested markdown by age: <90d none · 90–180 10% · 180–270 20% · 270–365 30% · >365 40–60%.',
  'recommended action': 'The suggested next step for the leftover stock, from the ageing and sales rules.',
  'value (cost)': 'Available pieces × cost price — the money tied up at cost.',
  'value (mrp)': 'Available pieces × MRP — the money tied up at full retail.',
  'month due': 'The month payment falls due, from the invoice or expected delivery plus payment terms.',
  'received (invoiced)': 'Amount due on goods already received and invoiced.',
  'projected (open po)': 'Amount that will fall due when open POs are delivered.',
  'pending approval': 'Quantity or value on lines still awaiting approval.',
  'history': 'Days of real inventory history since the product effectively launched. Under 45 the DOQ is built on a short window — read with caution.',
  'oos-day threshold': 'Above this many empty days in 45, the 45-day DOQ is not trusted and the year rate is used instead (Rules Master).',
  'ipdoq floor': 'The lowest daily rate any product is given, so slow sellers still get a minimum reorder (Rules Master).',
  'stock yesterday': 'Pieces in stock at Main Warehouse as of the snapshot day.',
  'days empty, last 45': 'Days with no stock at Main Warehouse in the last 45 days.',
  'days empty, last 365': 'Days with no stock at Main Warehouse in the last 365 days.',
  'sells a day': 'Pieces a day this SKU sells (45-day DOQ).',
  'where it stands': 'No stock yesterday · Was empty, back in stock · In stock all 45 days.',
  'excluded by': 'Who added this SKU to the exclusion list.',
  'category w/ gender': 'The product category with gender, as the feed holds it.',
  'completion': 'Share of ordered pieces the vendor actually delivered.',
  'on-time': 'Share of POs delivered by their expected or committed date.',
  'fill': 'Share of POs delivered in full (received ≥ ordered).',
  'otif': 'On Time In Full — the share of POs that were both on time and complete.',
  'pos': 'Number of POs behind this row.',
  'tendency': 'Whether this vendor tends to come in above or below the standard cost.',
  'avg δ / unit': 'Average difference per piece between the rate paid and the standard cost.',
  'avg δ %': 'Average difference from the standard cost, as a percentage.',
  'total δ value': 'Total margin difference across the POs: Σ (rate − standard) × quantity.',
  'δ / unit': 'Rate paid minus standard cost, per piece. Positive = paid more than standard.',
  'δ value': '(Rate − standard) × pieces — the margin difference on this PO.',
  'efob pos': 'POs contracted as E-FOB.',
  'cost δ (₹ total, top 3 this month)': 'Total rupees paid above standard cost on the top three POs this month.',
  'δ qty': 'Issued pieces minus approved pieces. Positive = bought more than the plan approved.',
  'approved value': 'Value of the approved plan quantity at the approved standard cost.',
  'issued value': 'Value of the POs actually issued in the month.',
  'issued qty': 'Pieces on real EasyEcom POs dated in the month.',
  'excess': 'Issued pieces above the approved quantity.',
  'excess %': 'Excess as a share of the approved quantity.',
  'excess value': 'Excess pieces × standard cost.',
  'job': 'Pieces planned through Job Work (SAADAA supplies fabric, vendor stitches).',
  'job work': 'Pieces planned through Job Work (SAADAA supplies fabric, vendor stitches).',
  'e-fob': 'Pieces planned as E-FOB (vendor supplies fabric, 45-day lead time).',
  'fob': 'Pieces planned as FOB (vendor supplies fabric, 75-day lead time).',
  'e-fob qty': 'Pieces planned as E-FOB.',
  'fob qty': 'Pieces planned as FOB.',
  'buy value (fob/e-fob)': 'Planned FOB and E-FOB pieces × their approved standard cost.',
  'buy value (job)': 'Planned Job Work pieces × the approved Job Work rate (stitching only — fabric is supplied by SAADAA).',
  'standard cost job · e-fob · fob': 'The approved Standard Cost per piece for each PO type, which values the plan.',
  'value to be bought': 'Planned pieces × the approved standard cost for each type, summed — the money the plan commits.',
  'actual qty': 'Pieces on real EasyEcom POs dated in this month for the product — what was actually ordered against the plan.',
  'actual issued quantity': 'Pieces on real EasyEcom POs dated in this month for the product.',
  'actual issued value': 'Value of the POs actually issued for the product this month.',
  'validation': 'Checks on the line — a missing approved cost, an issued quantity above plan, or a plan with nothing issued.',
  'arriving': 'Pieces still to arrive on this PO line.',
  'arriving qty': 'Pieces still to arrive.',
  'planned qty': 'Pieces the team planned to receive.',
  '% planned': 'Planned pieces ÷ arriving pieces — how much of what is due has been scheduled.',
  'stock, all warehouses': 'Pieces in stock across every warehouse for the colour, from the nightly snapshot.',
  'sizes in stock': 'Sizes with stock ÷ sizes arriving on this line — how many of the arriving sizes are already covered.',
  'ran out in last 45 days': 'Whether the colour had at least one empty day in the last 45.',
  'receiving week / month': 'When the team expects the goods — a specific week, or a whole month.',
  'qty expected': 'Pieces the team expects to receive in that week or month.',
  'variants': 'How many colours are on this row.',
  'po lines': 'One row per colour on an open PO.',
  'by product': 'The same rows rolled up per product code.',
  'by variant': 'The same rows rolled up per colour.',
  'by receiving month': 'The same rows rolled up by the month they are expected.',
  'ratings (1–5)': 'The four ratings from the de-boarding form — behaviour, work style, quality, process — 1 is very poor, 5 is excellent.',
  'pos done': 'POs the vendor has completed, from the completed-PO feed.',
  'late 15–29d / 30–60d / >60d': 'How many completed POs finished 15–29, 30–60 or more than 60 days after their expected delivery date.',
  'rejection %': 'Pieces failed at inbound QC ÷ pieces checked, across all goods receipts.',
  'resolvable': 'Whether the team thought the issue with the vendor could be fixed.',
};

/** Where a label means something specific on one page, keyed by route prefix. */
const PAGE: Record<string, Record<string, string>> = {
  '/': {
    'vendor': 'The vendor, with its code. Click a vendor to open its POs in the tracker.',
    'total': 'Pending pieces on the line, summed over sizes.',
    'po': 'The purchase order reference. Click a row to open its detail.',
    'utilization': 'Pieces on order ÷ PO capacity × 100; past 100% it reads "100% Over Utilised". "Not entered" = no capacity on the sheet.',
    'status': 'On Track, High Risk (a critical-path TNA stage past its planned date) or Overdue (past the expected delivery date).',
  },
  '/approvals': {
    'qty': 'Pieces on the item awaiting approval.',
    'value': 'Value of the item at the approved standard cost.',
    'pending': 'Items still awaiting a decision.',
    'approved': 'Items approved.',
  },
  '/po-approval': {
    'status': 'Where the PO stands: Draft, Approval Pending, Approved, Rejected or Rework. Approve and reject happen in Approvals.',
    'qty': 'Pieces on the PO across all colours and sizes.',
    'pending': 'Pieces on the issued PO not yet received.',
    // The deleted-requests log (admin only).
    'date log': 'The three dates a PO passes through: Req — the approval request was raised. Appr — it was approved internally. EasyCom — the PO was actually created in EasyCom. The last one is day 0 of the critical path: nothing can start before the PO exists there, so every TNA date is counted from it. "EasyCom not yet" on an approved PO means the order has not reached the vendor at all.',
    'deleted requests': 'Requests pulled back by whoever raised them (or by an admin) before approval. Nothing is erased — the row is kept here with the reason, so a request that left the queue can always be accounted for. An approved PO cannot be deleted.',
    'request': 'The Request ID it was raised under (PR-YYMM-0001). That id is now retired — a re-raise gets a new one.',
    'was': 'The status it was in at the moment it was deleted. Never Approved: an approved PO is a commitment and has to be closed, not deleted.',
    'raised by': 'Who created the request, and when.',
    'deleted by': 'Who deleted it, and when. Usually the person who raised it; an admin can delete anyone’s.',
    'reason': 'The reason given at deletion — mandatory, so this column is never empty.',
  },
  '/po-closure': {
    'status': 'Whether the PO has been closed out on EasyEcom after delivery.',
  },
  '/discontinue': {
    'status': 'Draft → Approval Pending → Approved / Rejected. Discontinue always needs an admin.',
    'qty': 'Available pieces still in the warehouse for this discontinued SKU.',
    'product': 'The product code; click for the SKUs behind it.',
  },
  '/issues': {
    'status': 'Open, In progress, Resolved or Dismissed. Resolved needs a line on what was done; Dismissed a line on why.',
    'days': 'Days from raise to resolve — or to today while still open. Red at 7 or more while open.',
    'category': 'What kind of issue this is — the category the routing works on.',
  },
  '/vendor-capacity': {
    'vendor': 'The vendor and its merchandiser. A red mark means the vendor has been de-boarded.',
    'type': 'The PO type from the vendor master (locked). It sets the lead days under it, which PO capacity is built on.',
    'in process': 'Pieces on approved POs with this vendor not yet received.',
    'utilization': 'Pieces on order ÷ PO capacity × 100; past 100% it reads "100% Over Utilised".',
    'last updated': 'When this vendor was last submitted. "Submitted · locked" = done this week; it reopens Saturday. Over 7 days without a submission = stale.',
  },
  '/vendor-deboarding': {
    'status': 'Submitted → Approved / Rejected / Rework. De-boarding always needs an admin; approval flags the vendor everywhere.',
    'reason': 'The reason for de-listing, from the six on the form; "Other" carries free text.',
    'vendor': 'The vendor being de-boarded, with its code.',
  },
  '/standard-cost': {
    'status': 'Where the cost stands in negotiation: proposed → target set → rate submitted → signed off.',
    'size': 'The size the cost applies to, where costs differ by size.',
    'stage': 'Where the cost is in the negotiation: propose (team) → set target (admin) → submit rate (team) → sign off (admin).',
  },
  '/buying-plan': {
    'status': 'Whether the issued POs match the plan: on plan, over approved, or not budgeted.',
    'approved': 'Pieces the approved plan said to buy.',
    'issued': 'Pieces on real EasyEcom POs dated in the month.',
    'pos': 'Number of POs issued for the product in the month.',
    'pending qty': 'Pieces on open POs for this product still to arrive.',
    'category': 'The product category from the product master.',
    'qty': 'Pieces planned.',
    'value': 'Pieces × the approved standard cost.',
    'total': 'The row total across PO types.',
    'colour': 'The colour of the dyed fabric on this line.',
  },
  '/cutting-register': {
    'status': 'Whether the data-capture link is live, used or expired.',
    'approval': 'Whether the cutting entry has been approved.',
  },
  '/receivable-plan': {
    'status': 'On Track, High Risk or Overdue — the same TNA rule as the Open PO Tracker. The raw EasyEcom status shows beneath.',
    'pos': 'How many POs are behind this row.',
  },
  '/adoption': {
    'status': 'Whether the user is active on the dashboard.',
  },
  '/users': {
    'status': 'Whether the tab is shown or hidden in the sidebar.',
  },
  '/feature-status': {
    'status': 'The label shown on the feature — live, beta, coming, and so on.',
  },
  '/ppm-prep': {
    'status': 'The PO status going into the PPM meeting.',
  },
  '/sync-status': {
    'status': 'Fresh, or stale when older than the Rules Master threshold.',
  },
  '/cost-analytics': {
    'pos': 'How many POs sit behind this row.',
    'type': 'The PO type the rate applies to.',
  },
  '/product-360': {
    'status': 'Whether the colour is out of stock, at risk, or covered.',
  },
  '/oos-calculation': {
    'on': 'The date the SKU was excluded.',
  },
};

/** The description for a header on a page, or null when the registry has none. */
export function headerHelp(label: string, pathname?: string | null): string | null {
  const key = norm(label);
  if (!key) return null;
  if (pathname) {
    const route = Object.keys(PAGE)
      .filter((p) => (p === '/' ? pathname === '/' : pathname.startsWith(p)))
      .sort((a, b) => b.length - a.length)[0];
    const hit = route ? PAGE[route][key] : undefined;
    if (hit) return hit;
  }
  return GLOBAL[key] ?? null;
}
