-- A PO raised here is a REQUEST, not a purchase order: EasyEcom issues the PO number.
-- Every request gets a unique id of its own, assigned by the database (PR-YYMM-0001), which
-- is what the dashboard shows and what the EasyEcom PO number is linked to once it exists.
-- Nothing here generates a PO reference any more.
create sequence if not exists public.sd_po_request_seq;

alter table public.sd_po_approval add column if not exists request_id text;

create or replace function public.sd_next_po_request_id()
returns text
language sql volatile
as $$
  select 'PR-' || to_char((now() at time zone 'Asia/Kolkata'), 'YYMM') || '-'
         || lpad(nextval('public.sd_po_request_seq')::text, 4, '0');
$$;

alter table public.sd_po_approval
  alter column request_id set default public.sd_next_po_request_id();

-- Existing rows keep their identity: oldest first, so the numbers read chronologically.
with numbered as (
  select id, row_number() over (order by coalesce(timestamp_created, created_at), id) as n
  from public.sd_po_approval
  where request_id is null
)
update public.sd_po_approval p
set request_id = 'PR-' || to_char(coalesce(p.timestamp_created, p.created_at, now()) at time zone 'Asia/Kolkata', 'YYMM')
                 || '-' || lpad(n.n::text, 4, '0')
from numbered n
where n.id = p.id;

select setval('public.sd_po_request_seq', greatest((select count(*) from public.sd_po_approval), 1));

alter table public.sd_po_approval alter column request_id set not null;
create unique index if not exists sd_po_approval_request_id_key on public.sd_po_approval (request_id);

comment on column public.sd_po_approval.request_id is
  'Unique id of the PO request, assigned here. The EasyEcom PO number (easycom_po_no) is linked to it at issuance; no PO number is generated by this dashboard.';
comment on column public.sd_po_approval.po_ref_num is
  'The PO reference as EasyEcom holds it. Filled at issuance alongside easycom_po_no - never generated here.';
